name: chat_shared
description: A shared logic for Chat.
author: Lukasz Huculak <lukasz.huculak@codete.com>

environment:
  sdk: '>=2.3.0-dev.0.1 <3.0.0'

dependencies:
  rxdart: ^0.22.0

dev_dependencies:
  test: ^1.6.3
  mockito: ^4.0.0
