name: chat_web
description: An absolute bare-bones web app.
author: Lukasz Huculak <lukasz.huculak@codete.com>

environment:
  sdk: '>=2.0.0-dev.55.0 <2.0.0'

dependencies:
  chat_shared:
    path: ../shared


dev_dependencies:
  build_runner: ^0.8.7
  build_web_compilers: ^0.4.0
