name: chat_web
description: An absolute bare-bones web app.
author: Lukasz Huculak <lukasz.huculak@codete.com>

environment:
  sdk: '>=2.3.0-dev.0.1 <3.0.0'

dependencies:
  chat_shared:
    path: ../shared

  react: ^4.4.2

  firebase: ^5.0.3

dev_dependencies:
  build_runner: ^1.4.0
  build_web_compilers: ^2.0.0
